using System;
using System.Collections.Generic;
using System.Linq;
using Gameplay;

namespace BattleriteBot.Addons.Champions
{
    public class AbilityData
    {
        public String Name;
        public Double Range;
        public Double MinRange;
        public Double Radius;
        public Double EnergyCost;
        public Boolean SharesCooldown;
        public Boolean HasCharges;
        public InputFlags InputFlags;
        public static Dictionary<String, List<AbilityData>> ChampionAbilityData = new Dictionary<string, List<AbilityData>>();
        static AbilityData()
        {
            var abilityData = new List<AbilityData>(); abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "DeadlyInjection", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ToxicBolt", Radius = 0, Range = 7.6, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "HealingPotion", Radius = 1.1, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = true, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Barrier", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "ClarityPotion", Radius = 1.9, Range = 8, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "PetrifyDart", Radius = 0, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "PanicFlask", Radius = 0, Range = 7.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "Roll", Radius = 0, Range = 5, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "CripplingGoo", Radius = 3, Range = 7.5, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Lucie", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "Sunlight", Radius = 1.3, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = true, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "CelestialRift", Radius = 2.2, Range = 9, MinRange = 7, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "CelestialSplit", Radius = 2.2, Range = 8, MinRange = 6.5, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Sunrise", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "LunarStrike", Radius = 1.75, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "PrismaticStrike", Radius = 0, Range = 4.5, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "AstralBeam", Radius = 0, Range = 10, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            abilityData.Add(new AbilityData { Name = "CrescentGale", Radius = 0, Range = 9.5, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "CrescentStrike", Radius = 1.9, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            ChampionAbilityData.Add("Sirius", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "Eat", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Pummel", Radius = 2.2, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "MeatBolt", Radius = 0, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "CrushingBlow", Radius = 1.6, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Rush", Radius = 0.7, Range = 11.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Berserk", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "BoulderToss", Radius = 1.9, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "Smack", Radius = 3.8, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "Tremor", Radius = 2.5, Range = 0, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Rook", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "RevolverShot", Radius = 0, Range = 7.6, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "SnapShot", Radius = 0, Range = 11.5, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Snipe", Radius = 0, Range = 11.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "BlastVault", Radius = 2, Range = 7, MinRange = 6, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "SmokeBomb", Radius = 3, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Stealth", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "DisablingShot", Radius = 0, Range = 10.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "JunkShot", Radius = 0, Range = 5, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "ExplosiveShells", Radius = 0, Range = 12, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Jade", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "ReapingScythe", Radius = 2, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "SinisterStrike", Radius = 2, Range = 4.5, MinRange = 3, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Consume", Radius = 1.25, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "ClawOfTheUndying", Radius = 0, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ClawOfTheWicked", Radius = 0, Range = 7.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "NetherVoid", Radius = 1.6, Range = 8, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "ShadowBeast", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            abilityData.Add(new AbilityData { Name = "DefiledBlade", Radius = 1.9, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "ShadowBolt", Radius = 0, Range = 11, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            ChampionAbilityData.Add("RuhKaan", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "Fireball", Radius = 0, Range = 7.6, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "FireStorm", Radius = 0, Range = 9.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "SearingFire", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 50, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "SearingDisplacement", Radius = 1.5, Range = 8, MinRange = 4, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "MoltenChains", Radius = 2.4, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Volcano", Radius = 1.8, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "MoltenFist", Radius = 1, Range = 4.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "FireWall", Radius = 0.6, Range = 2.5, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "InfernalDisplacement", Radius = 1.2, Range = 10, MinRange = 10, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Ashka", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "HandOfCorruption", Radius = 0, Range = 7.4, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "HandOfPunishment", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "HandOfJudgement", Radius = 0, Range = 9.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "InhibitorsGuard", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "WujuReform", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "Crush", Radius = 1.6, Range = 9, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = true, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Shatter", Radius = 1.25, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = true, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "KineticEnergy", Radius = 0.75, Range = 7, MinRange = 7, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "PowersCombined", Radius = 0.75, Range = 6.75, MinRange = 6.75, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Varesh", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "SoulBolt", Radius = 0, Range = 7.8, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "OtherSide", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "SoulTransfer", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "SpiritGuide", Radius = 0, Range = 8.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "SoulDrain", Radius = 2.3, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "SpiritRift", Radius = 2.3, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "MalevolentSpirit", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "Pixie", Radius = 0, Range = 3, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "AncestralSpirit", Radius = 0, Range = 7, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Poloma", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "SpearSlash", Radius = 1.9, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "Impale", Radius = 0.8, Range = 1.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "TempestRush", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Fleetfoot", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Kunju", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "Harpoon", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = true, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Javelin", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = true, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "TendonSwing", Radius = 2.6, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "Whirlwind", Radius = 2, Range = 0, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Shifu", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "ChaosGrip", Radius = 0, Range = 6, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Displace", Radius = 1, Range = 5.5, MinRange = 5.5, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "ArcaneWard", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ArcaneBarrier", Radius = 1.25, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "Shackle", Radius = 1, Range = 8.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "TomeOfDestruction", Radius = 0, Range = 5, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "GrimoireOfChaos", Radius = 3, Range = 4.5, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            abilityData.Add(new AbilityData { Name = "SiphonLife", Radius = 0, Range = 5, MinRange = 0, EnergyCost = 50, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ArcaneFire", Radius = 0, Range = 6.3, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            ChampionAbilityData.Add("Ezmo", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "WarAxe", Radius = 1.9, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "BloodAxe", Radius = 0, Range = 9.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "WarStomp", Radius = 2.2, Range = 8, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ValiantLeap", Radius = 2.2, Range = 8, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Bulwark", Radius = 1.25, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "ShieldSlam", Radius = 1, Range = 6, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ShieldDash", Radius = 0.5, Range = 4.8, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "WarShout", Radius = 3, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "HeroicCharge", Radius = 0.8, Range = 14, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Bakko", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "Surprise", Radius = 0, Range = 7, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Instinct", Radius = 0, Range = 5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "ForestSanctuary", Radius = 3, Range = 8.25, MinRange = 1.1, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "MrStumpy", Radius = 3, Range = 8.25, MinRange = 1.1, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "BoomBloom", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "Gust", Radius = 0, Range = 3.5, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "ForceOfNature", Radius = 0, Range = 10, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            abilityData.Add(new AbilityData { Name = "Nourish", Radius = 1.3, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = true, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Thwack", Radius = 0, Range = 7.6, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            ChampionAbilityData.Add("Blossom", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "SlicingWindsActivate", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "SwordSlash", Radius = 2, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "Retribution", Radius = 0, Range = 3.25, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "HeavenlyStrike", Radius = 0.5, Range = 2.25, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Parry", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "TectonicShock", Radius = 0, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "SeismicShock", Radius = 0, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "DragonPalm", Radius = 0, Range = 4, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "WrathOfTheTiger", Radius = 0.75, Range = 9.5, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Raigon", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "GuidedArrow", Radius = 0, Range = 10.5, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "HuntingArrow", Radius = 0, Range = 8.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "SeekersArrow", Radius = 0.4, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "SteadyShot", Radius = 0, Range = 10.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "BlackArrow", Radius = 0, Range = 8, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "RainOfArrows", Radius = 2, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "BearTrap", Radius = 1.1, Range = 7.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "Prowl", Radius = 1, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "DragonSlayer", Radius = 0, Range = 30, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Jumong", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "BashCombo", Radius = 1.9, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "StormMace", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "ShockVault", Radius = 0, Range = 5.5, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Spring", Radius = 0, Range = 4.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "ElectricShield", Radius = 100, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "ThunderSlam", Radius = 1, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ThunderClap", Radius = 2.5, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "ChargedStrike", Radius = 2.7, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "LightningStrike", Radius = 2.75, Range = 7, MinRange = 0.5, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Freya", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "Moth", Radius = 0, Range = 8, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "Vomit", Radius = 3.5, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Bloodsucker", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Infest", Radius = 0.4, Range = 7.5, MinRange = 5, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Queen", Radius = 2.5, Range = 8, MinRange = 1.1, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "BrainBug", Radius = 0, Range = 8, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Arachnophobia", Radius = 1.725, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "Swarm", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "ScarabPack", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Pestilus", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "ChronoBolt", Radius = 0, Range = 11, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "SandsOfTime", Radius = 0, Range = 7.6, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "RejuvenatingSands", Radius = 1.1, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = true, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "ShiftingSands", Radius = 1, Range = 8, MinRange = 5, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Chronoflux", Radius = 1.8, Range = 12, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "TimeBender", Radius = 1.25, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "Quicksand", Radius = 1.8, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "StoneGlass", Radius = 1.8, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "TimeTravel", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Oldur", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "RazorBoomerang", Radius = 0, Range = 7.7, MinRange = 7.7, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "SpinningBoomerang", Radius = 0, Range = 10, MinRange = 10, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "XStrike", Radius = 0, Range = 8.5, MinRange = 5.5, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Haste", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Zephyr", Radius = 1.75, Range = 4, MinRange = 4, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "WindStrike", Radius = 2.4, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "WindBomb", Radius = 2.2, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "Tornado", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "CompanionCall", Radius = 0.5, Range = 10, MinRange = 4, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Taya", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "BladeFlurry_01_", Radius = 1.9, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "SludgeSpit", Radius = 0, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ToxinMuck", Radius = 1.9, Range = 8, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "FrogLeap", Radius = 1.6, Range = 5.75, MinRange = 4, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Deceit", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Camouflage", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "NoxiousLunge", Radius = 1, Range = 5.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "ToxinBlades", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "VenomWind", Radius = 1, Range = 10, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Croak", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "DefensiveMatrix", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Blaster", Radius = 0, Range = 7.6, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "ChargedBolt", Radius = 0, Range = 6, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "MagneticOrbAlternate", Radius = 0.8, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "SkyStrikeCounter", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "PlasmaPrison", Radius = 2, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "PlasmaWall", Radius = 0.6, Range = 2.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "MegaSphere", Radius = 0, Range = 14, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "Pinball", Radius = 1, Range = 13.5, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Destiny", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "TrickShot", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "Spotlight", Radius = 2.2, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "GrandConjuration", Radius = 0, Range = 10.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Mindgame", Radius = 0.75, Range = 6.5, MinRange = 4, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "MirrorImage", Radius = 0.75, Range = 6.5, MinRange = 4, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Portal", Radius = 1.6, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "SheepTrick", Radius = 1.75, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "RabbitForm", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "ThePrestige", Radius = 0.5, Range = 7, MinRange = 2, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Zander", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "HammerOfJustice", Radius = 1.9, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "HolyLight", Radius = 1.3, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = true, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Crusade", Radius = 0.6, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Intervene", Radius = 0.7, Range = 6, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Sanctuary", Radius = 3, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "DivineShield", Radius = 1.5, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "Smite", Radius = 2.4, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "LawBringer", Radius = 0, Range = 6, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "AegisOfValor", Radius = 0.45, Range = 11, MinRange = 11, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Ulric", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "Ascension", Radius = 0.75, Range = 5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "JetStream", Radius = 0, Range = 8, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Dismissal", Radius = 2, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "SoaringThunder", Radius = 1.5, Range = 5.5, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "DragonRoar", Radius = 0.9, Range = 7, MinRange = 2, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "Dominion", Radius = 2.7, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "DragonStorm", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            abilityData.Add(new AbilityData { Name = "ShockBlast", Radius = 0.8, Range = 8.75, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "StormBolt", Radius = 0, Range = 8.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            ChampionAbilityData.Add("ShenRao", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "KatarCombo2", Radius = 0.6, Range = 1.7, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "BloodKunai", Radius = 0, Range = 9.5, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ShadowStar", Radius = 0, Range = 8, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "PuncturingStrike", Radius = 1, Range = 6, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ElusiveStrikeCharged", Radius = 1, Range = 8.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "ShadowStalk", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "HookShot", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "DeadlyBlow", Radius = 2.4, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "PhantomShadow", Radius = 0.7, Range = 9, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Jamila", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "Splinter", Radius = 0, Range = 7.8, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "IceLance", Radius = 0, Range = 9.5, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Snowboard", Radius = 2.2, Range = 9, MinRange = 4, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "IceBlock", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "GlacialPrism", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "SnowCone", Radius = 0, Range = 5.2, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "ColdSnap", Radius = 2, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "PolarBarrierAlt", Radius = 0, Range = 8, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "Avalanche", Radius = 0, Range = 14, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Alysia", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "RootClaw", Radius = 2.2, Range = 2.2, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "RootNetwork", Radius = 2, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "BurrowAlternate", Radius = 1.45, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "EvilClutch", Radius = 0.9, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "EntanglingRoots", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "BarbedHusk", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "DeadRoots", Radius = 1.5, Range = 8, MinRange = 8, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            abilityData.Add(new AbilityData { Name = "ThornBarrage", Radius = 0, Range = 9.5, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "DireThorns", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability2 });
            ChampionAbilityData.Add("Thorn", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "FlameThrower", Radius = 0, Range = 5, MinRange = 0, EnergyCost = 50, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Boomstick", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "RocketLauncher", Radius = 0, Range = 9, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "JetPack", Radius = 0.8, Range = 11, MinRange = 7, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "Zap", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "ConcussionShot", Radius = 0, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "Tazer", Radius = 0, Range = 10.5, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "TractorBeam", Radius = 0, Range = 8, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "MachineGun", Radius = 0, Range = 13.5, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Iva", abilityData.ToArray().ToList());
            abilityData.Clear();
            abilityData.Add(new AbilityData { Name = "Overflow", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "VolatileWater", Radius = 0, Range = 7.6, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability1 });
            abilityData.Add(new AbilityData { Name = "HealingWave", Radius = 1.3, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = true, InputFlags = InputFlags.Ability2 });
            abilityData.Add(new AbilityData { Name = "Dive", Radius = 0, Range = 6, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability3 });
            abilityData.Add(new AbilityData { Name = "TidalWave", Radius = 2, Range = 0, MinRange = 0, EnergyCost = 0, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability4 });
            abilityData.Add(new AbilityData { Name = "UnstableBubble", Radius = 1.6, Range = 10, MinRange = 0, EnergyCost = 25, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 | InputFlags.EX });
            abilityData.Add(new AbilityData { Name = "BubbleBarrier", Radius = 1.6, Range = 10, MinRange = 0, EnergyCost = 0, SharesCooldown = true, HasCharges = false, InputFlags = InputFlags.Ability5 });
            abilityData.Add(new AbilityData { Name = "BubbleShield", Radius = 0, Range = 0, MinRange = 0, EnergyCost = 25, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability6 });
            abilityData.Add(new AbilityData { Name = "Jaws", Radius = 2.3, Range = 11, MinRange = 0, EnergyCost = 100, SharesCooldown = false, HasCharges = false, InputFlags = InputFlags.Ability7 });
            ChampionAbilityData.Add("Pearl", abilityData.ToArray().ToList());



            ChampionAbilityData["Iva"][0].Range = 6.8f;
            ChampionAbilityData["Raigon"][2].Range = 5.5f;
            ChampionAbilityData["Raigon"][3].MinRange = 5.0f;
            ChampionAbilityData["Raigon"][3].Range = 9.0f;
            ChampionAbilityData["Taya"][0].MinRange = 0.0f;
            ChampionAbilityData["Taya"][2].MinRange = 0.0f;
        }
    }
}